version: "3.9"

services:

  sql:
    image: mcr.microsoft.com/mssql/server:2019-CU9-ubuntu-16.04
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - sql_volume:/var/opt/mssql
    ports:
      - 1433:1433

  mongo:
    image: mongo:4.4.4
    restart: unless-stopped
    volumes:
      - mongo_config_volume:/data/configdb
      - mongo_volume:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:6.2
    volumes:
      - redis_volume:/data
    ports:
      - 6380:6379

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.11.0
    restart: unless-stopped
    volumes:
      - azurite_volume:/data
    ports:
      - 10000:10000
      - 10001:10001

  seq:
    image: datalust/seq:2021.1
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq_volume:/data
    ports:
      - 5342:80
      - 5341:5341

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data/

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  sql_volume:
  mongo_config_volume:
  mongo_volume:
  redis_volume:
  azurite_volume:
  seq_volume:
  elastic_volume: